### ISSUE TITLE
[Feat]: Get OIDs

### ISSUE THREAD

**Issue by jmcc94** [bitfocus/companion-module-generic-snmp#2]
The ability to get OIDs from devices, and show them as variables / feedback would be very beneficial.

Use Cases: 
- POE status on port
- POE power draw

**Comment by ShuheiUda** [comment]
@phillipivan @estilles 
Thank you for providing great module in the recent release! (3.4)
Is there any plan to implement SNMP Get function?

**Comment by phillipivan** [comment]
Have you got any specific ideas regarding how it might work?

**Comment by phillipivan** [comment]
In case that is a little obtuse here are some things to think about:
- Are the OIDs for returned data defined in the module config, in actions, or feedbacks? 
- Is the polling on a set interval, presumably with a new config field, or manually as part of an action? 
- Does the module create variables for these OIDs (if they are defined in actions or feedbacks that might work like the Yamaha RCP module) or is the data returned to a custom variable?

**Comment by ShuheiUda** [comment]
@phillipivan Thank you for prompt reply.

When centrally managing multiple network devices that support SNMP, it would be very convenient to achieve the following:

- Poll the value of an OID every few seconds and use that value as the text for a button (using it as a variable).
- After executing an SNMP Set as a “Press action,” retrieve feedback using SNMP Get to verify whether the value was correctly changed.

For instance, if you could retrieve the power on/off status of individual outlets in a PDU (such as the Raritan PX3) using SNMP Get and then reflect that status on buttons (so that pressing a button toggles the outlet on or off), that would be quite useful.

**Comment by phillipivan** [comment]
So how do you propose to get the poll interval? From a config field that's used for all values?

How to determine which OIDs to get? Those used for actions, or something else?

Does the module create variables for all of these or return the value to a custom variable?

**Comment by phillipivan** [comment]
Implemented in 2.1.0
